/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_romantics_jni_Main */

#ifndef _Included_org_romantics_jni_Main
#define _Included_org_romantics_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_romantics_jni_Main
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_romantics_jni_Main_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_romantics_jni_Main
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_romantics_jni_Main_sub
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
